name: Stock Checker

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual run

jobs:
  check-stock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run stock checker
        env:
          DISCORD_WEBHOOK_URL: ${{ https://discord.com/api/webhooks/1299602576622358548/N-MHMR8PsdSlbaVj24AlC_shQBtwYecQ7FBZBzARwVg15bLgt9EB-PbPJQ0uDZ46X9G6 }}
        run: python check_stock.py
